sudo: required
services:
    - docker

before_install:
    - docker build -t mfarhan/docker-react -f Dockerfile.dev .

install:
    - bundle install

scripts:
    - docker run mfarhan/docker-react npm run test -- --coverage